### ISSUE TITLE
Add goals, requirements & expectations

### ISSUE THREAD

**Issue by leoboehm** [leoboehm/2048#1]

**Comment by carolina-cza** [comment]
**Goals:**
- functioning 2048 game

**Requirements:**
- pygame
- Object-oriented programming
- connecting the code with the visualization

**Learning Outcomes:**
- working with pygame
- Object-oriented programming
- Teamwork
- Time management

**Grading criteria:**
- applying what you have learned in the lecture
- use new tools
- readability of the code
- activity on git
- presentation

![image](https://github.com/leoboehm/2048/assets/152898637/ece1736c-0484-4855-b050-86627ef05cc2)

**Comment by leoboehm** [comment]
added text & sketch to wiki
